// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Demo.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Demo.Models.LHD214", b =>
                {
                    b.Property<string>("LHDID")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LHDGender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LHDName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("LHDID");

                    b.ToTable("LHD214s");
                });

            modelBuilder.Entity("Demo.Models.Movie", b =>
                {
                    b.Property<string>("MovieID")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MovieGender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MovieName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("MovieID");

                    b.ToTable("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
